### ISSUE TITLE
no_std Support

### ISSUE THREAD

**Issue by pinkforest** [dalek-cryptography/x25519-dalek#111]
Related

- ~~https://github.com/dalek-cryptography/x25519-dalek/issues/88~~ - Red herring - not this crate

## rand_core?/getrandom

It seems getrandom is brought by rand_core which isn't optional - that stops thumb building

```
    --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.2.8/src/lib.rs:268:9
    |
268 | /         compile_error!("target is not supported, for more information see: \
269 | |                         https://docs.rs/getrandom/#unsupported-targets");
```

https://github.com/pinkforest/x25519-dalek/actions/runs/4395315721/jobs/7697018808

Maybe we can make the get_random weak and gate via getrandom feature ?

This ofc requires some work around API re: providing randomness

**Comment by tarcieri** [comment]
This is unrelated to `std`: it's just a target that `getrandom` doesn't have support for.

That's why it's a feature and why things that require randomness use the `RngCore` trait: so the feature can be disabled.

The solution is to not enable the feature on these platforms.

**Comment by pinkforest** [comment]
Yeah I mean it's part of no_std support as --no-default-features was the one that failed and that came up

**Comment by tarcieri** [comment]
Aah, yeah this is the problem:

```
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }
```

Instead there should be a `getrandom` feature which activates `rand_core/getrandom`

**Comment by tarcieri** [comment]
Looks like it was changed in #95, although I'm not sure why as that PR does not reference `OsRng`, which is the main API provided by enabling `getrandom`

**Comment by pinkforest** [comment]
I'll send a PR to fix it

**Comment by pinkforest** [comment]
PR's up:
- https://github.com/dalek-cryptography/x25519-dalek/pull/112
