### ISSUE TITLE
Optional `Secret` types via features

### ISSUE THREAD

**Issue by pinkforest** [dalek-cryptography/x25519-dalek#114]
`ReusableSecret` is optional feature

Should `StaticSecret` be optional that can also make `rand_core` optional ?
- https://github.com/dalek-cryptography/x25519-dalek/issues/116

To that matter should `EphemeralSecret` be optional as well ? :thinking:

**Comment by tarcieri** [comment]
To me this crate's whole purpose is providing a simple interface for ECDHE.

If people want patterns that go beyond ECDHE, they should be using `curve25519-dalek` directly, IMO.

**Comment by pinkforest** [comment]
Yup so we can make `StaticSecret` optional (with it's warning) and leave EphemeralSecret as ECDHE "baseline"

**Comment by pinkforest** [comment]
`StaticSecret` was made optional so this can be closed
