### ISSUE TITLE
Functions that generate secrets should take &mut arguments rather than returning secret data on the stack.

### ISSUE THREAD

**Issue by canndrew** [dalek-cryptography/x25519-dalek#13]
I'm trying to build a crypto library that uses dalek and I'd like to avoid copying secret data around as much as possible. Ideally, functions like `generate_secret` should take a `&mut [u8; 32]` so that the data can be written to the exact place I want to keep it and so that I can zero the data after use.

This would be a very trivial change to the API and I'm happy to do a PR if you're down with it.

Thanks for the great library btw!

**Comment by isislovecruft** [comment]
Hi @canndrew! Thanks for the suggestion!

When passing in an `&mut T`, I'm not sure that the underlying pointer remains constant? Rust of course guarantees that nothing else will mutate it simultaneously, but no guarantees that the data won't move in the process.

I think the long-term fix for this is to do the suggestion in #9 by implementing key types (similarly as in done in [ed25519-dalek](https://github.com/dalek-cryptography/ed25519-dalek) which `impl Drop` and use `clear_on_drop::Clear` to zero out secrets.
