### ISSUE TITLE
Update documentation and avoid duplication

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/x25519-dalek#17]
Following #15, the documentation needs to be updated; right now it's duplicated across some markdown files and the source files.

**Comment by DebugSteven** [comment]
I can do this!

**Comment by isislovecruft** [comment]
This ended up breaking the doctests because there's no way to comment out/make invisible test setup code when it's in the README (afaik). I guess we'll have to ignore the tests? Although, I kind of dislike that the doctests could get out of sync and we might not notice.

**Comment by hdevalence** [comment]
Fixed in #60
