### ISSUE TITLE
subtl dependency broken again

### ISSUE THREAD

**Issue by aep** [dalek-cryptography/x25519-dalek#19]
subtle 0.7 was yanked, but x25519-dalek  requires exactly curve25519-dalek 0.19, which depends on exactly subtle 0.7 

```
    Updating git repository `https://github.com/quininer/rust-hacl-star.git`
    Updating crates.io index
error: failed to select a version for the requirement `subtle = "^0.7"`
  candidate versions found which didn't match: 2.0.0, 1.0.0
  location searched: crates.io index
required by package `curve25519-dalek v0.19.0`
    ... which is depended on by `x25519-dalek v0.3.0`
    ... which is depended on by `carrier v0.8.0 (/home/aep/proj/devguard/carrier2)`

```

**Comment by blackbeam** [comment]
As a workaround you can clone registry:
```sh
git clone --bare https://github.com/rust-lang/crates.io-index.git
```
then revert `61302e43a378df5d0b0bd190ad8d6ae76d76d56b` and use this regestry as an index in your `~/.cargo/config`:
```toml
[registry]
index = "file:///tmp/crates.io-index.git"
```

**Comment by hdevalence** [comment]
This should be fixed via crates.io now, sorry about that.

**Comment by aep** [comment]
thanks, any chance the curve25519-dalek will be updated some day?

**Comment by hdevalence** [comment]
Yes, it's done in the `develop` branch, there just needs to be a `0.4.0` release.

**Comment by aep** [comment]
ack, thanks
