### ISSUE TITLE
Rendering API docs on docs.rs

### ISSUE THREAD

**Issue by DebugSteven** [dalek-cryptography/x25519-dalek#23]
I noticed the API docs for `x25519` & `curve25519` aren't rendering properly on doc.rs.
The docs.rs build fails on
```
error: error reading `.cargo/registry/src/github.com-1ecc6299db9ec823/curve25519-dalek-0.13.2/rustdoc-include-katex-header.html`: No such file or directory (os error 2)
```
You can see the full error log here: https://docs.rs/crate/x25519-dalek/0.4.2/builds/137497

The file it can't find was referenced here:
https://github.com/dalek-cryptography/x25519-dalek/blob/65f94124f4e738ad75d0c1bab5ae6fa0acffd415/Cargo.toml#L22-L24

The reason for this error is because docs.rs recently moved servers & the cargo cache was lost.

To fix this for `x25519` & `curve25519` the name of the file for
`.cargo/registry/src/github.com-1ecc6299db9ec823/curve25519-dalek-1.0.1/docs/assets/rustdoc-include-katex-header.html` needs to be changed & then republish the crate.

**Comment by isislovecruft** [comment]
Ooops.. looks like this didn't fix it?

**Comment by DebugSteven** [comment]
I saw there's still a similar issue happening, just with the new file name.
```
error: error reading `.cargo/registry/src/github.com-1ecc6299db9ec823/curve25519-dalek-1.0.1/docs/assets/rustdoc-include-katex-header.html`: No such file or directory (os error 2)
```
Full log here: https://docs.rs/crate/x25519-dalek/0.4.3/builds/138154
I'm happy to look into with @QuietMisdreavus if that's useful.

**Comment by hdevalence** [comment]
https://docs.rs/x25519-dalek/0.6.0/x25519_dalek/ seems to render correctly now.
