### ISSUE TITLE
Builds failing due to issue with "rand" crate

### ISSUE THREAD

**Issue by thanethomson** [dalek-cryptography/x25519-dalek#27]
See Travis: https://travis-ci.org/dalek-cryptography/x25519-dalek/jobs/482814498

It appears as though the `rand` crate is causing a build failure using Rust nightly.

**Comment by hdevalence** [comment]
This looks like https://github.com/rust-random/rand/issues/688 , not sure why it's causing problems now.

**Comment by hdevalence** [comment]
This should be fixed with `0.6`.
