### ISSUE TITLE
Documentation and example on bare bytes API

### ISSUE THREAD

**Issue by zer0x64** [dalek-cryptography/x25519-dalek#30]
I checked out the bare-bytes API for use with FFI. The API is easy enough for people who knows a bit about Elliptic Curves and Diffie-Hellman, but can be pretty confusing for people with limited knowledge. 
Without any modification to the code itself, I suggest to add a usage example to the x25519() function in the docs.
I can write the example, test it and make a PR, but I just wanted to know your input about it before doing it!

**Comment by hdevalence** [comment]
Hi, that'd be great!

**Comment by pakipaki2000** [comment]
Please do it, that would be awesome

**Comment by isislovecruft** [comment]
Thanks for this @zer0x64!
