### ISSUE TITLE
secret from bytes

### ISSUE THREAD

**Issue by aep** [dalek-cryptography/x25519-dalek#31]
with x25519_dalek::generate_public gone, there is no way to construct a secret anymore except from randomness. How is serializtion/deserialization supposed to work?

Unfortunately we have to upgrade to 0.4, since 0.3 has yanked dependencies

**Comment by aep** [comment]
thanks!

i got scared because multiplying  by X25519_BASEPOINT_BYTES (as new code suggests) did not look the same as ED25519_BASEPOINT_TABLE (old generate_public).

thanks for confirming this is the correct migration.

**Comment by hdevalence** [comment]
Sorry for not updating the docs in time, we're trying to roll everything over to the stable versions as fast as possible, to minimize the chance of something that's not easily upgradeable using an old version.
