### ISSUE TITLE
Ephemral secret keys seem to be too ephemeral.

### ISSUE THREAD

**Issue by pinkisemils** [dalek-cryptography/x25519-dalek#32]
As of version `0.4`, there's no way to construct a secret key from bytes. As such, it's not possible to serialize a secret key. In our use case, the key exchange is considered to be expensive, so we'd like to serialize the private key to disk and read it from disk at a later time. So it'd be nice to be able to still construct an `x25519` private key from bytes.

Now, since you have introduced the `Ephemeral{Secret,Public}Key`, I understand that you wouldn't want them to be serialized. Would there be any chance of having non-ephemeral `x25519` key types, or just a plain `fn generate_public(private_key: [u8;32]) -> [u8; 32]` exposed in this library?

**Comment by zer0x64** [comment]
Hi!

I faced the same problem, having to serialize the private key to pass them to other languages using FFI.

From what I saw, this seems to be for misuse resistance. If you cannot serialize the secret key, there is less chance that it will leak. Also, using a static private key for this protocol is not a good practice. For the performance issue, the private key is really easy to generate: It's simply 32 random bytes. The public key, however, may be a lot more expansive to generate from the private key.

If you're sure you know what you're doing, the library expose a "bare-bytes API" that deals directly with bytes array. I am currently writing an example for the documentation as per https://github.com/dalek-cryptography/x25519-dalek/issues/30.

**Comment by isislovecruft** [comment]
Hi @pinkisemils! If I understand your use case correctly, I think the `StaticSecret` type should work for you. Please note that reusing Diffie-Hellman secrets is extremely not recommended, and if you can spare the expense it's much safer to use the `EphemeralSecret` type.
