### ISSUE TITLE
Add feature to enable the avx2_backend from curve25519

### ISSUE THREAD

**Issue by dignifiedquire** [dalek-cryptography/x25519-dalek#38]
I was wondering if there is a specific reason that is currently not proxied through, like it is in ed25519-dalek.

**Comment by hdevalence** [comment]
The reason is that the AVX2 backend implements accelerated Edwards curve arithmetic, but X25519 uses Montgomery arithmetic. So enabling it wouldn't have any effect, because it's unused.

**Comment by dignifiedquire** [comment]
thanks.....I should have realized that, but ETooManyCryptoPrimtives in my head..
