### ISSUE TITLE
Sample code uses deprecated "rand_os"

### ISSUE THREAD

**Issue by Andrew-Shay** [dalek-cryptography/x25519-dalek#59]
The sample code in the [documentation](https://docs.rs/x25519-dalek/0.6.0/x25519_dalek/index.html) uses the deprecated `rand_os`
https://docs.rs/rand_os/0.2.2/rand_os/
> Deprecated since 0.2.2: OsRng is now provided by rand_core and rand

Is there a sample that uses `rand_core` or `rand`?

Here's a snippet that _seems_ to work but **I don't know if it's secure**

```rust
use rand_core::{OsRng};
let mut alice_csprng = OsRng;
```

**Comment by hdevalence** [comment]
@Andrew-Shay Yes, that looks right to me.  I'll try to update the docs tomorrow.
