### ISSUE TITLE
Bump MSRV in `2.0.0` instead of requiring `zeroize =1.3.0`

### ISSUE THREAD

**Issue by paolobarbolini** [dalek-cryptography/x25519-dalek#81]
Hello, I saw you released the first pre-release for 2.0 but I couldn't find the branch to send the PR myself, so I'll write this here:
could version 2 bump it's MSRV instead of requiring `zeroize` `=1.3.0` ? This will break compiling with other crates that require zeroize  `>1.3.0`

**Comment by isislovecruft** [comment]
Hi @paolobarbolini! Thanks for the suggestion. I'll bump up the MSRV for the prerelease to 1.51. (I think that's what zeroize was requiring?)

**Comment by isislovecruft** [comment]
The patch for this (#82) has been released in 2.0.0-pre.1.

**Comment by paolobarbolini** [comment]
Thank you @isislovecruft
