### ISSUE TITLE
Build for ESP32 microcontroller

### ISSUE THREAD

**Issue by DavidCarl** [dalek-cryptography/x25519-dalek#88]
Hello.

I am currently trying to use this library for a project that needs to run on a ESP32. This means that we have no operating system and no STD. But the library should be in the category "No standard library" which should be fine for me in this case.

I am using the ESP32 build chain and this project to set it up, which is this: https://github.com/esp-rs/rust-build

But when attempting to build it I recieve the following error:

```
error: linking with `ldproxy` failed: exit status: 1
...
  = note: Running ldproxy
          Error: Linker /home/carl/.espressif/tools/xtensa-esp32-elf-clang/esp-13.0.0-20211203-x86_64-unknown-linux-gnu/bin/xtensa-esp32-elf-gcc failed: exit status: 1
          STDERR OUTPUT:
          /home/carl/.espressif/tools/xtensa-esp32-elf-clang/esp-13.0.0-20211203-x86_64-unknown-linux-gnu/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/carl/Documents/git/github/esp-rs/esp32-build/target/xtensa-esp32-espidf/debug/deps/libclear_on_drop-7f6bb154f7984c2b.rlib: error adding symbols: file format not recognized
          collect2: error: ld returned 1 exit status
```

[full log here](https://gist.github.com/DavidCarl/232c59a5911c8623569c0390470944c4)

Hope this is something you can help me with.

**Comment by pinkforest** [comment]
The error here seems not to indicate any error with this crate ? 

We've added no_std into the CI and I am able to compile ot thumb target which doesn't have std.

**Comment by tarcieri** [comment]
Notably the error appears to be here:

> libclear_on_drop-7f6bb154f7984c2b.rlib: error adding symbols: file format not recognized

This appears to be some issue with the [`clear_on_drop`](https://crates.io/crates/clear_on_drop) crate, which is not a dependency of any of the crates in this project.
