### ISSUE TITLE
Types with Drop to hold the secret keys (and others if needed)

### ISSUE THREAD

**Issue by ustulation** [dalek-cryptography/x25519-dalek#9]
[libsodium provides](https://github.com/jedisct1/libsodium-doc/blob/master/helpers/memory_management.md#securing-memory-allocations) a mem-zeroing functionality which gets called from the rust versions (e.g. [rust_sodium](https://github.com/maidsafe/rust_sodium)) for at-least all the secret keys which are user-defined types with `Drop`. There is no such management in dalek. Just wandering on what the opinions are on this:
- It is important and we need it and `dalek` is ready to provide it
- It is important but the user is expected to do the wrapping but `dalek` wouldn't see this as its goal
- It's not needed (if so any reasons would be good to know)

**Comment by isislovecruft** [comment]
Hi @ustulation! Thanks for the suggestion.

This would be great. Preferably, if we could do this by:

[ ] Implementing types for keys/secrets, as in [ed25519-dalek](https://github.com/dalek-cryptography/ed25519-dalek)
[ ] Using `clear_on_drop::clear::Clear` to implement zeroing secrets and ephemeral values on `Drop`, as [here](https://github.com/dalek-cryptography/ed25519-dalek/blob/master/src/ed25519.rs#L180)
[ ] Changing the current functions to be methods on these types

I'd gladly accept help and provide mentorship (if needed) on this issue if anyone were excited to contribute.

**Comment by brntsllvn** [comment]
Happy to contribute. Not sure the coding chops required but maybe DM me to discuss? @brntsllvn
I have a fair amount of time this week and would appreciate mentorship!

**Comment by DebugSteven** [comment]
I'd like to take this issue.

**Comment by isislovecruft** [comment]
Oh gosh, I wasn't expecting so much interest! Thanks all!

@brntsllvn If it's okay with you, @DebugSteven DMed me nearly immediately after I posted asking for help, and I had already started to fill them in on the details... I'm sorry for missing your comment, and I'm happy to try to find another issue for you to work on, if you like? (Unfortunately we have three classes of issues right now: 1. "needs research" 2. "hard problems" and 3. "easy tasks" and not so many of number 3.)

**Comment by georgio** [comment]
> Oh gosh, I wasn't expecting so much interest! Thanks all!
> 
> @brntsllvn If it's okay with you, @DebugSteven DMed me nearly immediately after I posted asking for help, and I had already started to fill them in on the details... I'm sorry for missing your comment, and I'm happy to try to find another issue for you to work on, if you like? (Unfortunately we have three classes of issues right now: 1. "needs research" 2. "hard problems" and 3. "easy tasks" and not so many of number 3.)

Please let me know if you come up with anything, I'd love to contribute to the project.

**Comment by isislovecruft** [comment]
Implemented by @DebugSteven in #15 and merged for the 0.4.0 release. Thanks @DebugSteven!
