### ISSUE TITLE
Do you really need to borrow self here?

### ISSUE THREAD

**Issue by BoisterousCoder** [dalek-cryptography/x25519-dalek#91]
https://github.com/dalek-cryptography/x25519-dalek/blob/53bb1a3989874ffe526a90fd225b5cb1c18f06c3/src/x25519.rs#L78

I am trying to use this function however my ephemeral key is a pointer and it has to be that way due to some other packages I am using. Is there a reason that the `self` on this line of code can't just be `&self`?

P.S, I am sorry if I did something wrong here. This is my first time submitting an issue on GitHub.

**Comment by pinkforest** [comment]
Yes it takes the ownership. Ephemeral secret key [is supposed to be short lived and destroyed after](https://github.com/dalek-cryptography/x25519-dalek/blob/53bb1a3989874ffe526a90fd225b5cb1c18f06c3/src/x25519.rs#L63-70).

There is a [feature](https://github.com/dalek-cryptography/x25519-dalek/blob/main/Cargo.toml#L57) - [reusable_secrets](https://github.com/dalek-cryptography/x25519-dalek/blob/53bb1a3989874ffe526a90fd225b5cb1c18f06c3/src/x25519.rs#L99) that takes a [borrow](https://github.com/dalek-cryptography/x25519-dalek/blob/53bb1a3989874ffe526a90fd225b5cb1c18f06c3/src/x25519.rs#L126)
